web:
    image: market_web
    ports:
        - "8004:8004"
orderbook:
    image: market_orderbook
    ports:
        - "8001:8001"
    links:
        - ticker
        - ledger
        - redis
ticker:
    image: market_ticker
    ports:
        - "8003:8003"
    links:
        - web
        - redis
        - mongo
ledger:
    image: market_ledger
    ports:
        - "8002:8002"
redis:
    image: redis
mongo:
    ports:
        - "27017:27017"
    image: mongo

