web_lb:
    build: ./web_lb
    ports:
        - "80:80"
    links:
        - web
        - orderbook
        - ticker
        - ledger
web:
    build: ./web_service
    ports:
        - "8080"
orderbook:
    build: ./orderbook_service
    ports:
        - "8080"
    links:
        - web
        - ticker
        - ledger
        - redis
ticker:
    build: ./ticker_service
    ports:
        - "8080"
    links:
        - redis
        - mongo
ledger:
    build: ./ledger_service
    ports:
        - "8080"
redis:
    image: redis
mongo:
    ports:
        - "27017:27017"
    image: mongo

