version: '2'
services:
    web:
        #image: nickstefan/web_service
        build: ./web_service
        ports:
            - "8004:8004"
    orderbook:
        #image: nickstefan/orderbook_service
        build: ./orderbook_service
        ports:
            - "8001:8001"
        links:
            - redis
    ticker:
        build: ./ticker_service
        #image: nickstefan/ticker_service
        ports:
            - "8003:8003"
        links:
            - web
            - redis
            - mongo
    ledger:
        build: ./ledger_service
        ports:
            - "8002:8002"
        #image: nickstefan/ledger_service
    redis:
        image: redis
    mongo:
        ports:
            - "27017:27017"
        image: mongo
    
