version: '2'
services:
    web_lb:
        build: ./web_lb
        restart: always
        ports:
            - "80:80"
        links:
            - web
            - orderbook1
            - orderbook2
            - ticker
            - ledger
    web:
        build: ./web_service
        ports:
            - "8080"
    orderbook1:
        build: ./orderbook_service
        ports:
            - "8080"
        links:
            - web
            - ticker
            - ledger
            - redis
    orderbook2:
        build: ./orderbook_service
        ports:
            - "8080"
        links:
            - web
            - ticker
            - ledger
            - redis
    ticker:
        build: ./ticker_service
        environment:
            # docker-machine IP. not for production use!
            MONGOHOST: "192.168.99.100"
        ports:
            - "8080"
        links:
            - redis
            - mongo
    ledger:
        build: ./ledger_service
        ports:
            - "8080"
    redis:
        image: redis
    mongo:
        ports:
            - "27017:27017"
        image: mongo
    
