web_lb:
    cpu_shares: 2048
    image: nickstefan/market_web_lb
    ports:
        - "80:80"
    links:
        - web
        - orderbook
        - ticker
        - ledger
web:
    cpu_shares: 1024
    image: nickstefan/market_web
    ports:
        - "8080"
orderbook:
    cpu_shares: 2048
    image: nickstefan/market_orderbook
    ports:
        - "8080"
    links:
        - web
        - ticker
        - ledger
        - redis
ticker:
    cpu_shares: 512
    image: nickstefan/market_ticker
    ports:
        - "8080"
    links:
        - redis
        - mongo
ledger:
    cpu_shares: 512
    image: nickstefan/market_ledger
    ports:
        - "8080"
redis:
    cpu_shares: 1024
    image: redis
mongo:
    cpu_shares: 512
    ports:
        - "27017:27017"
    image: mongo

