version: '2'
services:
    web_lb:
        build: ./web_lb
        restart: always
        ports:
            - "80:80"
        links:
            - web
            - orderbook1
            - orderbook2
            - ticker
            - ledger
    web:
        #image: nickstefan/web_service
        build: ./web_service
        ports:
            - "8080"
    orderbook1:
        #image: nickstefan/orderbook_service
        build: ./orderbook_service
        ports:
            - "8080:8080"
        links:
            - ticker
            - ledger
            - redis
    orderbook2:
        #image: nickstefan/orderbook_service
        build: ./orderbook_service
        ports:
            - "8080"
        links:
            - redis
    ticker:
        build: ./ticker_service
        #image: nickstefan/ticker_service
        ports:
            - "8080"
        links:
            - redis
            - mongo
    ledger:
        build: ./ledger_service
        ports:
            - "8080"
        #image: nickstefan/ledger_service
    redis:
        image: redis
    mongo:
        ports:
            - "27017:27017"
        image: mongo
    
