web_lb:
    image: nickstefan/market_web_lb
    ports:
        - "80:80"
    links:
        - web
        - orderbook1
        - orderbook2
        - ticker
        - ledger
web:
    image: nickstefan/market_web
    ports:
        - "8080"
orderbook1:
    image: nickstefan/market_orderbook1
    ports:
        - "8080"
    links:
        - web
        - ticker
        - ledger
        - redis
orderbook2:
    image: nickstefan/market_orderbook2
    ports:
        - "8080"
    links:
        - web
        - ticker
        - ledger
        - redis
ticker:
    image: nickstefan/market_ticker
    ports:
        - "8080"
    links:
        - redis
        - mongo
ledger:
    image: nickstefan/market_ledger
    ports:
        - "8080"
redis:
    image: redis
mongo:
    ports:
        - "27017:27017"
    image: mongo

