apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: ledger
  name: ledger
spec:
  replicas: 1
  selector:
    service: ledger
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: ledger
    spec:
      containers:
      - image: nickstefan/market_ledger
        imagePullPolicy: ""
        name: ledger
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
