apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: orderbook
  name: orderbook
spec:
  replicas: 1
  selector:
    service: orderbook
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: orderbook
    spec:
      containers:
      - image: nickstefan/market_orderbook
        imagePullPolicy: ""
        name: orderbook
        ports:
        - containerPort: 8080
        resources:
            requests:
                cpu: "3"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
