apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: orderbook1
  name: orderbook1
spec:
  replicas: 1
  selector:
    service: orderbook1
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: orderbook1
    spec:
      containers:
      - image: nickstefan/market_orderbook1
        imagePullPolicy: ""
        name: orderbook1
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
