kind: Service
apiVersion: v1
metadata:
  name: redis
  creationTimestamp: 
  labels:
    service: redis
spec:
  ports: 
  - name: '6379'
    protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 0
  selector:
    service: redis
status:
  loadBalancer: {}
