apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: web
  name: web
spec:
  replicas: 1
  selector:
    service: web
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: web
    spec:
      containers:
      - image: nickstefan/market_web
        imagePullPolicy: ""
        name: web
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
