apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: web-lb
  name: web-lb
spec:
  replicas: 1
  selector:
    service: web-lb
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: web-lb
    spec:
      containers:
      - image: nickstefan/market_web_lb
        imagePullPolicy: ""
        name: web-lb
        ports:
        - containerPort: 80
        resources: 
            requests:
                cpu: "3"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
