apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: web_lb
  name: web_lb
spec:
  replicas: 1
  selector:
    service: web_lb
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: web_lb
    spec:
      containers:
      - image: nickstefan/market_web_lb
        imagePullPolicy: ""
        name: web_lb
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
