kind: Service
apiVersion: v1
metadata:
  name: web-lb
  creationTimestamp: 
  labels:
    service: web-lb
spec:
  type: LoadBalancer
  ports:
  - name: '80'
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 0
  selector:
    service: web-lb
status:
  loadBalancer: {}
